In [15]:
import numpy as np
import pandas as pd

from pandas import DataFrame

In [16]:
# filling missing values using fillna(), replace(), and interpolate()
data = {'names':['steve','john','richard','sarah','randy','michael','julie'],
       'age':[20,22,20,21,24,23,22],
       'gender':['Male','Male','Male','Female','Male','Male','Female'],
       'rank':[2,1,4,5,3,7,6]  
       }
ranking_df = DataFrame(data)
ranking_df.iloc[2:5,1] = np.nan
ranking_df.iloc[3:6,3] = np.nan
ranking_df.iloc[3,:] = np.nan
ranking_df

     names   age  gender  rank
0    steve  20.0    Male   2.0
1     john  22.0    Male   1.0
2  richard   NaN    Male   4.0
3      NaN   NaN     NaN   NaN
4    randy   NaN    Male   NaN
5  michael  23.0    Male   NaN
6    julie  22.0  Female   6.0

In [17]:
# handling missing values
ranking_df.isnull()

   names    age  gender   rank
0  False  False   False  False
1  False  False   False  False
2  False   True   False  False
3   True   True    True   True
4  False   True   False   True
5  False  False   False   True
6  False  False   False  False

In [18]:
ranking_df.notnull()

   names    age  gender   rank
0   True   True    True   True
1   True   True    True   True
2   True  False    True   True
3  False  False   False  False
4   True  False    True  False
5   True   True    True  False
6   True   True    True   True

In [21]:
bool_series = pd.isnull(ranking_df['age'])
ranking_df[bool_series]

     names  age gender  rank
2  richard  NaN   Male   4.0
3      NaN  NaN    NaN   NaN
4    randy  NaN   Male   NaN

In [22]:
# fill missing values in a data frame

#fill all missing with 0
ranking_df.fillna(0)

     names   age  gender  rank
0    steve  20.0    Male   2.0
1     john  22.0    Male   1.0
2  richard   0.0    Male   4.0
3        0   0.0       0   0.0
4    randy   0.0    Male   0.0
5  michael  23.0    Male   0.0
6    julie  22.0  Female   6.0

In [25]:
# Use ffill() to fill each missing value with the preceding value in the same column:
ranking_df.ffill()

     names   age  gender  rank
0    steve  20.0    Male   2.0
1     john  22.0    Male   1.0
2  richard  22.0    Male   4.0
3  richard  22.0    Male   4.0
4    randy  22.0    Male   4.0
5  michael  23.0    Male   4.0
6    julie  22.0  Female   6.0

In [26]:
# Use ffill() to fill each missing value with the next value in the same column:
ranking_df.bfill()

     names   age  gender  rank
0    steve  20.0    Male   2.0
1     john  22.0    Male   1.0
2  richard  23.0    Male   4.0
3    randy  23.0    Male   6.0
4    randy  23.0    Male   6.0
5  michael  23.0    Male   6.0
6    julie  22.0  Female   6.0

In [34]:
# fill with interpolated values
numeric_cols = ranking_df.select_dtypes(include='number').columns
ranking_df[numeric_cols] = ranking_df[numeric_cols].interpolate(method='linear')
ranking_df

     names    age  gender  rank
0    steve  20.00    Male   2.0
1     john  22.00    Male   1.0
2  richard  22.25    Male   4.0
3      NaN  22.50     NaN   4.5
4    randy  22.75    Male   5.0
5  michael  23.00    Male   5.5
6    julie  22.00  Female   6.0

In [35]:
# drop rows and columns that have NaN
ranking_df.dropna()

     names    age  gender  rank
0    steve  20.00    Male   2.0
1     john  22.00    Male   1.0
2  richard  22.25    Male   4.0
4    randy  22.75    Male   5.0
5  michael  23.00    Male   5.5
6    julie  22.00  Female   6.0

In [36]:
#drop all rows and columns that contain only nas
ranking_df.dropna(how='all')

     names    age  gender  rank
0    steve  20.00    Male   2.0
1     john  22.00    Male   1.0
2  richard  22.25    Male   4.0
3      NaN  22.50     NaN   4.5
4    randy  22.75    Male   5.0
5  michael  23.00    Male   5.5
6    julie  22.00  Female   6.0

In [37]:
#drop columns that contain at least one missing values
ranking_df.dropna(axis = 1)

     age  rank
0  20.00   2.0
1  22.00   1.0
2  22.25   4.0
3  22.50   4.5
4  22.75   5.0
5  23.00   5.5
6  22.00   6.0

In [38]:
#drop rows that contain at least one missing values
ranking_df.dropna(axis = 0)

     names    age  gender  rank
0    steve  20.00    Male   2.0
1     john  22.00    Male   1.0
2  richard  22.25    Male   4.0
4    randy  22.75    Male   5.0
5  michael  23.00    Male   5.5
6    julie  22.00  Female   6.0