In [1]:
import pandas as pd

df = pd.DataFrame({
    'name': ['Anna', 'Ben', 'Chris', 'Diana'],
    'age': [25, 32, 28, 40],
    'salary': [60000, 75000, 68000, 90000]
})

In [2]:
df.query('age > 30')

    name  age  salary
1    Ben   32   75000
3  Diana   40   90000

In [3]:
import pandas as pd

df1 = pd.DataFrame({
    'Name': ['Anna', 'Ben'],
    'Age': [25, 30]
})

df2 = pd.DataFrame({
    'Name': ['Chris', 'Diana'],
    'Age': [28, 35]
})

In [4]:
df1
df2

    Name  Age
0  Chris   28
1  Diana   35

In [5]:
pd.concat([df1, df2], axis=0)

    Name  Age
0   Anna   25
1    Ben   30
0  Chris   28
1  Diana   35

In [6]:
pd.concat([df1, df2], axis=0, ignore_index=True)

    Name  Age
0   Anna   25
1    Ben   30
2  Chris   28
3  Diana   35

In [8]:
pd.concat([df1, df2], axis=1)

   Name  Age   Name  Age
0  Anna   25  Chris   28
1   Ben   30  Diana   35